name: "CI/CD FlakyDoctor"
description: "GitHub Action for FlakyDoctor"
author: "Quint van Oorschot"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.12

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Clone FlakyDoctor
      shell: bash
      run: |
        git clone --depth=2 https://github.com/Intelligent-CAT-Lab/FlakyDoctor.git
        echo "FlakyDoctor cloned into $(pwd)/FlakyDoctor"
