# name: "CI/CD FlakyDoctor"
# description: "GitHub Action for FlakyDoctor"
# author: "Quint van Oorschot"

# runs:
#   using: "composite"
#   steps:
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: 3.10.12

#     - name: Upgrade pip
#       shell: bash
#       run: python -m pip install --upgrade pip

#     - name: Clone FlakyDoctor
#       shell: bash
#       run: |
#         git clone --depth=2 https://github.com/Intelligent-CAT-Lab/FlakyDoctor.git
#         echo "FlakyDoctor cloned into $(pwd)/FlakyDoctor"

name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

inputs:
  openai_api_key:
    description: "OpenAI key (optional if set in env)"
    required: false

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.12"

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    # if the user passed the key via `with:`, expose it to the job env
    - name: Export API key (optional)
      shell: bash
      run: |
        if [ -n "${{ inputs.openai_api_key }}" ]; then
          echo "OPENAI_API_KEY=${{ inputs.openai_api_key }}" >> "$GITHUB_ENV"
        fi

    - name: Debug action path
      shell: bash
      run: |
        echo "github.action_path = ${{ github.action_path }}"
        echo "---- ls -la ${{ github.action_path }} ----"
        ls -la "${{ github.action_path }}"
        echo "---- find (top 3 levels) ----"
        # no tree in the runner/container, so use find
        find "${{ github.action_path }}" -maxdepth 4 -print

    - name: Run CICD FlakyDoctor
      shell: bash
      run: |
        python "${{ github.action_path }}/CICD-FlakyDoctor.py"
