# name: "CI/CD FlakyDoctor"
# description: "GitHub Action for FlakyDoctor"
# author: "Quint van Oorschot"

# runs:
#   using: "composite"
#   steps:
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: 3.10.12

#     - name: Upgrade pip
#       shell: bash
#       run: python -m pip install --upgrade pip

#     - name: Clone FlakyDoctor
#       shell: bash
#       run: |
#         git clone --depth=2 https://github.com/Intelligent-CAT-Lab/FlakyDoctor.git
#         echo "FlakyDoctor cloned into $(pwd)/FlakyDoctor"

name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

inputs:
  openai_api_key:
    description: "OpenAI key (optional if set in env)"
    required: false

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.12"

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip --no-cache-dir

    - name: Export API key (optional)
      shell: bash
      run: |
        if [ -n "${{ inputs.openai_api_key }}" ]; then
          echo "OPENAI_API_KEY=${{ inputs.openai_api_key }}" >> "$GITHUB_ENV"
        fi

    # 🔎 REAL DEBUG that works in a container
    - name: Debug filesystem
      shell: bash
      run: |
        set -x
        echo "pwd = $(pwd)"
        echo "whoami = $(whoami)"
        echo "GITHUB_WORKSPACE='${GITHUB_WORKSPACE}'"
        echo "=== / (top level) ==="
        ls -la /
        echo "=== /__w (if mounted) ==="
        ls -la /__w 2>/dev/null || true
        echo "=== /__w/_actions (if mounted) ==="
        ls -R /__w/_actions 2>/dev/null | head -n 2000 || true
        echo "=== GITHUB_WORKSPACE (if exists) ==="
        if [ -n "${GITHUB_WORKSPACE}" ] && [ -d "${GITHUB_WORKSPACE}" ]; then
          ls -R "${GITHUB_WORKSPACE}" | head -n 2000
        else
          echo "GITHUB_WORKSPACE not mounted or empty"
        fi

    # ✅ pull the repo again INSIDE the container, where we control the path
    - name: Fetch FlakyDoctor source
      shell: bash
      run: |
        set -e
        TARGET=/tmp/flakydoctor-src
        rm -rf "$TARGET"
        git clone --depth=1 https://github.com/quintoorschot/CICD-FlakyDoctor.git "$TARGET"
        echo "Cloned into $TARGET"
        ls -R "$TARGET" | head -n 2000

    # 🧪 actually run your script from the clone
    - name: Run FlakyDoctor
      shell: bash
      run: |
        set -e
        SRC=/tmp/flakydoctor-src
        # change this if your file has a different name / path
        SCRIPT="$SRC/CICD-FlakyDoctor.py"
        if [ ! -f "$SCRIPT" ]; then
          echo "ERROR: $SCRIPT not found. Contents of $SRC:"
          ls -R "$SRC"
          exit 1
        fi
        python "$SCRIPT"
