# name: "CI/CD FlakyDoctor"
# description: "GitHub Action for FlakyDoctor"
# author: "Quint van Oorschot"

# runs:
#   using: "composite"
#   steps:
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: 3.10.12

#     - name: Upgrade pip
#       shell: bash
#       run: python -m pip install --upgrade pip

#     - name: Clone FlakyDoctor
#       shell: bash
#       run: |
#         git clone --depth=2 https://github.com/Intelligent-CAT-Lab/FlakyDoctor.git
#         echo "FlakyDoctor cloned into $(pwd)/FlakyDoctor"

name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

inputs:
  openai_api_key:
    description: "OpenAI key (optional if set in env)"
    required: false

runs:
  using: composite
  steps:
    # 1. use container python (already has javalang)
    - name: Show container Python
      shell: bash
      run: |
        which python3
        python3 --version
        # prove javalang is there
        python3 - << 'PY'
        import importlib
        m = importlib.import_module("javalang")
        print("javalang", getattr(m, "__version__", "OK"))
        PY

    # 2. expose key if given
    - name: Export API key (optional)
      shell: bash
      run: |
        if [ -n "${{ inputs.openai_api_key }}" ]; then
          echo "OPENAI_API_KEY=${{ inputs.openai_api_key }}" >> "$GITHUB_ENV"
        fi

    # 3. find the real dir of THIS action
    - name: Locate action directory
      id: locate
      shell: bash
      run: |
        HOST="${{ github.action_path }}"
        CONT="${HOST/\/home\/runner\/work/\/__w}"

        if [ -d "$HOST" ]; then
          ROOT="$HOST"
        elif [ -d "$CONT" ]; then
          ROOT="$CONT"
        else
          echo "Could not find action dir"
          find /__w/_actions -maxdepth 5 -print 2>/dev/null || true
          exit 1
        fi

        echo "Using action dir: $ROOT"
        echo "root=$ROOT" >> "$GITHUB_OUTPUT"

        echo "=== action dir (maxdepth 3) ==="
        find "$ROOT" -maxdepth 3 -print

    # 4. make the path the script expects
    - name: Make workspace alias
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        WS="${GITHUB_WORKSPACE:-/workspace}"
        TARGET="$WS/CICD-FlakyDoctor"

        echo "Workspace is: $WS"
        echo "Action root is: $ROOT"
        echo "Script expects: $TARGET"

        # if there's already a dir, leave it; if not, symlink to action
        if [ -e "$TARGET" ]; then
          echo "$TARGET already exists:"
          ls -la "$TARGET"
        else
          mkdir -p "$WS"
          ln -s "$ROOT" "$TARGET"
          echo "Created symlink: $TARGET -> $ROOT"
        fi

        # show the exact file the script was crying about
        ls -la "$TARGET/FlakyDoctor/src" || true

    # 5. run the script (now the path exists)
    - name: Run CICD FlakyDoctor
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        SCRIPT="$ROOT/CICD-FlakyDoctor.py"
        if [ ! -f "$SCRIPT" ]; then
          echo "ERROR: $SCRIPT not found"
          exit 1
        fi
        echo "Running: python3 \"$SCRIPT\""
        python3 "$SCRIPT"
