name: "CI/CD FlakyDoctor"
description: "GitHub Action for FlakyDoctor"
author: "Quint van Oorschot"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.12
        cache: pip

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install FlakyDoctor
      shell: bash
      run: python -m pip install git+https://github.com/quintoorschot/CICD-FlakyDoctor