name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

inputs:
  openai_api_key:
    description: "OpenAI key (optional if set in env)"
    required: false

runs:
  using: composite
  steps:

    - name: Locate action directory
      id: locate
      shell: bash
      run: |
        HOST="${{ github.action_path }}"
        CONT="${HOST/\/home\/runner\/work/\/__w}"

        if [ -d "$HOST" ]; then
          ROOT="$HOST"
        elif [ -d "$CONT" ]; then
          ROOT="$CONT"
        else
          echo "Could not find action dir"
          find /__w/_actions -maxdepth 5 -print 2>/dev/null || true
          exit 1
        fi

    - name: Make workspace alias for script
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        WS="${GITHUB_WORKSPACE:-/workspace}"
        TARGET="$WS/CICD-FlakyDoctor"

        echo "Workspace: $WS"
        echo "Action root: $ROOT"
        echo "Target alias: $TARGET"

        if [ -e "$TARGET" ]; then
          echo "$TARGET already exists"
          ls -la "$TARGET" || true
        else
          mkdir -p "$WS"
          ln -s "$ROOT" "$TARGET"
          echo "Created symlink: $TARGET -> $ROOT"
        fi

        # just show the file the script was complaining about
        ls -la "$TARGET/FlakyDoctor/src" || true

    - name: Run CICD FlakyDoctor
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        SCRIPT="$ROOT/CICD-FlakyDoctor.py"
        if [ ! -f "$SCRIPT" ]; then
          echo "ERROR: $SCRIPT not found in $ROOT"
          ls -la "$ROOT"
          exit 1
        fi
        echo "Running: python3 \"$SCRIPT\""
        python3 "$SCRIPT"
