# .github/workflows/flakydoctor.yml
name: FlakyDoctor

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  flakydoctor:
    runs-on: ubuntu-latest
    # keep the container here — composite actions can't declare this
    container: ghcr.io/quintoorschot/cicd-flakydoc-env:latest

    steps:
      # this single step now pulls in all the logic from your action.yml
      - name: Run FlakyDoctor
        uses: quintoorschot/CICD-FlakyDoctor@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY != '' && secrets.OPENAI_API_KEY || secrets.OPEN_API_KEY }}
